=== sasd13/g2x/gedcom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT title (#PCDATA)>

<!ELEMENT gedcom (indi | fam)+>

<!ELEMENT indi (name?, titl?, (famx | event)*, obje*)>
<!ATTLIST indi id ID #REQUIRED>
<!ATTLIST indi sex (M | F) #IMPLIED>
<!ELEMENT name (#PCDATA)>

<!ELEMENT indix EMPTY>
<!ATTLIST indix ref IDREF #REQUIRED>
<!ATTLIST indix type (HUSB | WIFE | CHIL) #REQUIRED>

<!ELEMENT fam (indix | event | obje)+>
<!ATTLIST fam id ID #REQUIRED>

<!ELEMENT famx EMPTY>
<!ATTLIST famx ref IDREF #REQUIRED>
<!ATTLIST famx type (FAMC | FAMS) #REQUIRED>

<!ELEMENT event (#PCDATA | date | plac)*>
<!ATTLIST event type (BIRT | CHR | DEAT | BURI | MARR | DIV) #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT plac (#PCDATA)>

<!ELEMENT obje (form | titl | file)+>
<!ELEMENT form (#PCDATA)>
<!ELEMENT file (#PCDATA | form | titl)*>

=== sasd13/g2x/src/main/resources/test.ged.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xml2html.xsl" type="text/xsl"?>
<!DOCTYPE gedcom SYSTEM "gedcom.dtd">
<gedcom>
  <indi id="id-I1" sex="M">
    <name>Bob /Cox/</name>
    <famx ref="id-F1" type="FAMS" />
  </indi>
  <indi id="id-I2" sex="F">
    <name>Joann /Para/</name>
    <famx ref="id-F1" type="FAMS" />
  </indi>
  <indi id="id-I3" sex="M">
    <name>Bobby Jo /Cox/</name>
    <famx ref="id-F1" type="FAMC" />
  </indi>
  <fam id="id-F1">
    <indix ref="id-I1" type="HUSB" />
    <indix ref="id-I2" type="WIFE" />
    <event type="MARR" />
    <indix ref="id-I3" type="CHIL" />
  </fam>
</gedcom>
